### ISSUE TITLE
개발환경 관련 / certification 관련 오류

### ISSUE THREAD

**Issue by lgy1425** [medi-whale/drnoon_client#14]
* 제 로컬 환경에서 개발 할 수 있도록 localhost:5000 에 실행시키려면 어떤 설정을 해야 하나요? python run.py 로 하면 DB 정보를 못 찾던데 설정 방법을 알려주시면 감사하겠습니다.

* 제가 수정한 부분을 배포하려면 어떤 과정을 거쳐야 하는지 간단하게 정리해주시면 좋겠습니다. / 에러 로그를 보는 방법도 알려주세요.

* /certification/... 밑에 있는 route 들이 500 internal server error 가 나고 있는데 이 부분 봐주시면 감사하겠습니다. 

* 그리고 upload_api 요청시 계속 Failed to load resource: the server responded with a status of 413 (Request Entity Too Large) 413 에러가 나는데  이 에러는 처음 보는 것이라 혹시 upload_api 부분에서 바뀐게 있을까요?

- 인증 때문에 당장 기능이 이상 없이 작동하는게 중요해서 내일 아침에 봐주시면 감사하겠습ㄴ디ㅏ.

**Comment by essemfly** [comment]
- python run.py runserver 하면 가능합니다
- 개발환경설정파일들 전달드렸습니다. 에러 로그 방법도 같이 전달드립니다.
- /certification 및 /snec은 해결했습니다.
